import assert from "node:assert/strict";
import test from "node:test";
import { BLOCK, BLOCK_CATALOG, BLOCKS } from "../src/blocks.js";
import { BLOCK_IDS, ITEM_IDS } from "../src/content-ids.js";
import { getItem, isBlockItem, ITEM, ITEMS } from "../src/items.js";

// These are save-format regression markers, not a second configurable catalog.
const legacyBlocks = `
AIR GRASS DIRT STONE SAND OAK_LOG LEAVES PLANKS COBBLESTONE GLASS BRICK WATER
SNOW BEDROCK COAL_ORE BIRCH_LOG BIRCH_LEAVES GLOWSTONE RED_FLOWER YELLOW_FLOWER
SPRUCE_LOG SPRUCE_LEAVES ACACIA_LOG ACACIA_LEAVES JUNGLE_LOG JUNGLE_LEAVES
CHERRY_LOG CHERRY_LEAVES DARK_OAK_LOG DARK_OAK_LEAVES PALE_LOG PALE_LEAVES CACTUS
DEAD_BUSH TALL_GRASS PODZOL MUD MYCELIUM RED_MUSHROOM BROWN_MUSHROOM MUSHROOM_STEM
TERRACOTTA RED_TERRACOTTA ORANGE_TERRACOTTA YELLOW_TERRACOTTA WHITE_TERRACOTTA
RED_SAND SANDSTONE ICE PACKED_ICE BLUE_ICE SNOW_BLOCK GRAVEL CLAY MOSS DRIPSTONE
SCULK BAMBOO MANGROVE_LOG MANGROVE_LEAVES CORAL SEAGRASS IRON_ORE GOLD_ORE
DIAMOND_ORE COPPER_ORE REDSTONE_ORE EMERALD_ORE LAPIS_ORE OBSIDIAN NETHERRACK
SOUL_SAND BASALT BLACKSTONE CRIMSON_STEM CRIMSON_LEAVES WARPED_STEM WARPED_LEAVES
END_STONE PURPUR CHORUS LAVA TORCH CRAFTING_TABLE FURNACE CHEST WOOL TNT FARMLAND
WHEAT_CROP MELON PUMPKIN NETHER_PORTAL END_PORTAL SUGAR_CANE FERN LILY_PAD
SUNFLOWER PINK_PETALS SULFUR CINNABAR POTENT_SULFUR SULFUR_SPIKE CAVE_VINE GLOW_BERRIES
`
  .trim()
  .split(/\s+/);
const legacyItems = `
WOOD_PICKAXE STONE_PICKAXE IRON_PICKAXE DIAMOND_PICKAXE WOOD_AXE STONE_AXE
IRON_AXE DIAMOND_AXE WOOD_SWORD STONE_SWORD IRON_SWORD DIAMOND_SWORD WOOD_SHOVEL
STONE_SHOVEL IRON_SHOVEL DIAMOND_SHOVEL STICK COAL IRON_INGOT GOLD_INGOT DIAMOND
RAW_BEEF STEAK RAW_PORK COOKED_PORK RAW_CHICKEN COOKED_CHICKEN RAW_MUTTON
COOKED_MUTTON APPLE BREAD WHEAT SEEDS LEATHER FEATHER BONE ARROW GUNPOWDER STRING
FLINT_AND_STEEL BUCKET WATER_BUCKET IRON_ARMOR EGG ENDER_PEARL RAW_IRON RAW_GOLD
RAW_COPPER COPPER_INGOT BOW REDSTONE EMERALD LAPIS FLINT SLIME_BALL SHIELD
IRON_HELMET IRON_LEGGINGS IRON_BOOTS
`
  .trim()
  .split(/\s+/);
const shippedBlocks = Object.freeze({
  COPPER_BLOCK: 1024,
  BOOKSHELF: 1025,
  OAK_SLAB: 1026,
  OAK_STAIRS: 1027,
  OAK_DOOR: 1028,
  OAK_TRAPDOOR: 1029,
  OAK_FENCE: 1030,
  OAK_FENCE_GATE: 1031,
  LADDER: 1032,
  WHITE_BED: 1033,
  MAGMA_BLOCK: 1034,
  KELP: 1035,
  DEEPSLATE: 1036,
  SEA_LANTERN: 1037,
  COBBLED_DEEPSLATE: 1038,
  TUBE_CORAL_BLOCK: 1040,
  TUBE_CORAL: 1041,
  TUBE_CORAL_FAN: 1042,
  BRAIN_CORAL_BLOCK: 1043,
  BRAIN_CORAL: 1044,
  BRAIN_CORAL_FAN: 1045,
  BUBBLE_CORAL_BLOCK: 1046,
  BUBBLE_CORAL: 1047,
  BUBBLE_CORAL_FAN: 1048,
  FIRE_CORAL_BLOCK: 1049,
  FIRE_CORAL: 1050,
  FIRE_CORAL_FAN: 1051,
  HORN_CORAL_BLOCK: 1052,
  HORN_CORAL: 1053,
  HORN_CORAL_FAN: 1054,
  DEEPSLATE_COAL_ORE: 1060,
  DEEPSLATE_IRON_ORE: 1061,
  DEEPSLATE_COPPER_ORE: 1062,
  DEEPSLATE_GOLD_ORE: 1063,
  DEEPSLATE_REDSTONE_ORE: 1064,
  DEEPSLATE_DIAMOND_ORE: 1065,
  DEEPSLATE_LAPIS_ORE: 1066,
  DEEPSLATE_EMERALD_ORE: 1067,
  NETHER_GOLD_ORE: 1068,
  NETHER_QUARTZ_ORE: 1069,
  ANCIENT_DEBRIS: 1070,
  QUARTZ_BLOCK: 1071,
  DEAD_TUBE_CORAL_BLOCK: 1072,
  DEAD_TUBE_CORAL: 1073,
  DEAD_TUBE_CORAL_FAN: 1074,
  DEAD_BRAIN_CORAL_BLOCK: 1075,
  DEAD_BRAIN_CORAL: 1076,
  DEAD_BRAIN_CORAL_FAN: 1077,
  DEAD_BUBBLE_CORAL_BLOCK: 1078,
  DEAD_BUBBLE_CORAL: 1079,
  DEAD_BUBBLE_CORAL_FAN: 1080,
  DEAD_FIRE_CORAL_BLOCK: 1081,
  DEAD_FIRE_CORAL: 1082,
  DEAD_FIRE_CORAL_FAN: 1083,
  DEAD_HORN_CORAL_BLOCK: 1084,
  DEAD_HORN_CORAL: 1085,
  DEAD_HORN_CORAL_FAN: 1086,
  PRISMARINE: 1087,
  PRISMARINE_BRICKS: 1088,
  DARK_PRISMARINE: 1089,
  SPONGE: 1090,
  WET_SPONGE: 1091,
  GOLD_BLOCK: 1092,
  MOSSY_COBBLESTONE: 1093,
  NETHER_BRICKS: 1094,
  NETHER_BRICK_STAIRS: 1095,
  NETHER_BRICK_SLAB: 1096,
  NETHER_BRICK_FENCE: 1097,
  NETHER_WART_CROP: 1098,
  SPAWNER: 1099,
  COMPOSTER: 1100,
  LECTERN: 1101,
  CARTOGRAPHY_TABLE: 1102,
  SMITHING_TABLE: 1103,
});
const shippedItems = Object.freeze({
  PAPER: 65536,
  BOOK: 65537,
  QUARTZ: 65538,
  NETHERITE_SCRAP: 65539,
  GOLD_NUGGET: 65540,
  NETHERITE_INGOT: 65541,
  PRISMARINE_SHARD: 65542,
  PRISMARINE_CRYSTALS: 65543,
  NETHER_WART: 65544,
  NETHER_BRICK: 65545,
});
const newBlocks = `
BIRCH_PLANKS BIRCH_SLAB BIRCH_STAIRS BIRCH_DOOR BIRCH_TRAPDOOR BIRCH_FENCE BIRCH_FENCE_GATE
SPRUCE_PLANKS SPRUCE_SLAB SPRUCE_STAIRS SPRUCE_DOOR SPRUCE_TRAPDOOR SPRUCE_FENCE SPRUCE_FENCE_GATE
ACACIA_PLANKS ACACIA_SLAB ACACIA_STAIRS ACACIA_DOOR ACACIA_TRAPDOOR ACACIA_FENCE ACACIA_FENCE_GATE
JUNGLE_PLANKS JUNGLE_SLAB JUNGLE_STAIRS JUNGLE_DOOR JUNGLE_TRAPDOOR JUNGLE_FENCE JUNGLE_FENCE_GATE
CHERRY_PLANKS CHERRY_SLAB CHERRY_STAIRS CHERRY_DOOR CHERRY_TRAPDOOR CHERRY_FENCE CHERRY_FENCE_GATE
DARK_OAK_PLANKS DARK_OAK_SLAB DARK_OAK_STAIRS DARK_OAK_DOOR DARK_OAK_TRAPDOOR DARK_OAK_FENCE DARK_OAK_FENCE_GATE
PALE_OAK_PLANKS PALE_OAK_SLAB PALE_OAK_STAIRS PALE_OAK_DOOR PALE_OAK_TRAPDOOR PALE_OAK_FENCE PALE_OAK_FENCE_GATE
MANGROVE_PLANKS MANGROVE_SLAB MANGROVE_STAIRS MANGROVE_DOOR MANGROVE_TRAPDOOR MANGROVE_FENCE MANGROVE_FENCE_GATE
CRIMSON_PLANKS CRIMSON_SLAB CRIMSON_STAIRS CRIMSON_DOOR CRIMSON_TRAPDOOR CRIMSON_FENCE CRIMSON_FENCE_GATE
WARPED_PLANKS WARPED_SLAB WARPED_STAIRS WARPED_DOOR WARPED_TRAPDOOR WARPED_FENCE WARPED_FENCE_GATE
BAMBOO_PLANKS BAMBOO_SLAB BAMBOO_STAIRS BAMBOO_DOOR BAMBOO_TRAPDOOR BAMBOO_FENCE BAMBOO_FENCE_GATE
BAMBOO_BLOCK BARREL BLAST_FURNACE BREWING_STAND ENCHANTING_TABLE ANVIL CHIPPED_ANVIL
DAMAGED_ANVIL IRON_BLOCK SMOOTH_STONE CONDUIT TURTLE_EGG CARROT_CROP DRIED_KELP_BLOCK
`
  .trim()
  .split(/\s+/);
const newItems = `
OAK_BOAT BIRCH_BOAT SPRUCE_BOAT ACACIA_BOAT JUNGLE_BOAT CHERRY_BOAT DARK_OAK_BOAT
PALE_OAK_BOAT MANGROVE_BOAT BAMBOO_RAFT FISHING_ROD RAW_COD COOKED_COD RAW_SALMON
COOKED_SALMON TROPICAL_FISH PUFFERFISH INK_SAC BLACK_DYE SCUTE NAUTILUS_SHELL
HEART_OF_THE_SEA TREASURE_MAP NETHERITE_UPGRADE_TEMPLATE ENCHANTED_BOOK GLASS_BOTTLE
POTION SPLASH_POTION BLAZE_ROD BLAZE_POWDER SUGAR SPIDER_EYE FERMENTED_SPIDER_EYE
GHAST_TEAR MAGMA_CREAM GLOWSTONE_DUST CARROT GOLDEN_CARROT MELON_SLICE GLISTERING_MELON_SLICE
DRIED_KELP SHEARS WOOD_HOE STONE_HOE IRON_HOE DIAMOND_HOE COPPER_PICKAXE COPPER_AXE
COPPER_SWORD COPPER_SHOVEL COPPER_HOE GOLD_PICKAXE GOLD_AXE GOLD_SWORD GOLD_SHOVEL GOLD_HOE
NETHERITE_PICKAXE NETHERITE_AXE NETHERITE_SWORD NETHERITE_SHOVEL NETHERITE_HOE
LEATHER_HELMET LEATHER_CHESTPLATE LEATHER_LEGGINGS LEATHER_BOOTS
COPPER_HELMET COPPER_CHESTPLATE COPPER_LEGGINGS COPPER_BOOTS
GOLD_HELMET GOLD_CHESTPLATE GOLD_LEGGINGS GOLD_BOOTS
CHAINMAIL_HELMET CHAINMAIL_CHESTPLATE CHAINMAIL_LEGGINGS CHAINMAIL_BOOTS
DIAMOND_HELMET DIAMOND_CHESTPLATE DIAMOND_LEGGINGS DIAMOND_BOOTS
NETHERITE_HELMET NETHERITE_CHESTPLATE NETHERITE_LEGGINGS NETHERITE_BOOTS TURTLE_HELMET ROTTEN_FLESH
`
  .trim()
  .split(/\s+/);

test("all persisted legacy and previously shipped expansion identities are unchanged", () => {
  assert.equal(legacyBlocks.length, 105);
  assert.equal(legacyItems.length, 59);
  const expectedBlocks = {
    ...Object.fromEntries(legacyBlocks.map((symbol, id) => [symbol, id])),
    ...shippedBlocks,
  };
  const expectedItems = {
    ...Object.fromEntries(
      legacyItems.map((symbol, offset) => [symbol, 256 + offset])
    ),
    ...shippedItems,
  };
  for (const [symbol, id] of Object.entries(expectedBlocks)) {
    assert.equal(BLOCK_IDS[symbol], id, symbol);
    assert.equal(BLOCKS[id]?.id, id, symbol);
    assert.equal(ITEM[symbol], id, symbol);
    assert.equal(getItem(id)?.blockId, id, symbol);
  }
  for (const [symbol, id] of Object.entries(expectedItems)) {
    assert.equal(ITEM_IDS[symbol], id, symbol);
    assert.equal(ITEM[symbol], id, symbol);
    assert.equal(getItem(id)?.id, id, symbol);
    assert.equal(BLOCKS[id], undefined, symbol);
  }
  for (const [symbol, id] of Object.entries(BLOCK_IDS))
    assert.ok(Object.hasOwn(expectedBlocks, symbol) || id >= 1104, symbol);
  for (const [symbol, id] of Object.entries(ITEM_IDS))
    assert.ok(Object.hasOwn(expectedItems, symbol) || id >= 65546, symbol);
});

test("this content wave reserves its complete explicit block and ordinary-item mapping", () => {
  assert.equal(newBlocks.length, 91);
  assert.equal(newItems.length, 87);
  for (const [offset, symbol] of newBlocks.entries()) {
    const id = 1104 + offset;
    assert.equal(BLOCK_IDS[symbol], id, symbol);
    assert.equal(getItem(id)?.blockId, id, symbol);
  }
  for (const [offset, symbol] of newItems.entries()) {
    const id = 65546 + offset;
    assert.equal(ITEM_IDS[symbol], id, symbol);
    assert.equal(getItem(id)?.id, id, symbol);
    assert.ok(id > 65535, symbol);
  }
});

test("the real dense catalogs and sparse Uint16 block index contain no aliases or phantom entries", () => {
  const all = [...Object.values(BLOCK_IDS), ...Object.values(ITEM_IDS)];
  assert.equal(new Set(all).size, all.length);
  assert.equal(
    Object.keys(ITEM).length,
    all.length,
    "symbol collisions cannot hide a definition"
  );
  assert.equal(ITEMS.length, all.length);
  assert.equal(BLOCK_CATALOG.length, Object.keys(BLOCK_IDS).length);
  for (const [index, item] of ITEMS.entries()) {
    assert.equal(getItem(item.id), item);
    assert.ok(Object.isFrozen(item));
    assert.ok(index === 0 || ITEMS[index - 1].id < item.id);
  }
  const packed = Uint16Array.from(BLOCK_CATALOG, (block) => block.id);
  for (const [index, block] of BLOCK_CATALOG.entries()) {
    assert.ok(Number.isInteger(block.id) && block.id <= 65535);
    assert.equal(packed[index], block.id);
    assert.equal(BLOCKS[block.id], block);
    assert.equal(getItem(block.id).kind, "block");
    assert.equal(isBlockItem(block.id), true);
  }
  for (const id of Object.values(ITEM_IDS)) {
    assert.equal(BLOCKS[id], undefined);
    assert.equal(isBlockItem(id), false);
  }
  for (const symbol of ["OAK_PLANKS", "COD", "SALMON", "IRON_CHESTPLATE"])
    assert.equal(
      Object.hasOwn(ITEM, symbol),
      false,
      `${symbol} must not alias a persisted item`
    );
  assert.equal(BLOCK.PLANKS, 7);
  assert.ok(ITEM.RAW_COD > 65535 && ITEM.RAW_SALMON > 65535);
});
