import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { IDBFactory } from "fake-indexeddb";
import { ITEM } from "../src/items.js";
import { normalizeWorldComponents } from "../src/save-preflight.js";
import { exportWorldFile, parseWorldFile, WorldStorage } from "../src/storage.js";
import { generateTraderOffers, TRADING_PROFESSIONS } from "../src/trading-offers.js";
import { normalizeTradingSnapshot } from "../src/trading-state.js";
import { Trading } from "../src/trading.js";
import { createWorldContext } from "../src/world-spec.js";
import { inventoryStacks, traderFixture, tradeOptions } from "./progression-fixture.js";

// Generated by executing trading.js, trading-state.js and trading-offers.js
// from the fixture's actual sourceCommit via git show, not by trimming the new
// roster. HEAD registered a farmer, bought wheat three times, restocked once,
// then sold bread twice, and its own normalizer accepted the serialized result.
const fixture = JSON.parse(readFileSync(
  new URL("./fixtures/trading-v1-farmer.json", import.meta.url), "utf8"
));
const archived = () => structuredClone(fixture.archive);
const readAvailability = () => ({
  adult: true, alive: true, nitwit: false, available: true,
  dimension: "overworld", revision: 0,
});
const oldOptions = (time) => ({
  clock: { day: 3, time }, readAvailability,
  jobsiteUsable: () => true, validate: () => true,
});

test("genuine HEAD six-offer farmer survives current normalization and full world preflight", () => {
  const saved = archived();
  const context = createWorldContext(saved.world);
  const expected = saved.progression.trading;
  assert.equal(expected.npcs[0].offers.length, 6);
  assert.equal(expected.npcs[0].offers[1].uses, 2);
  assert.deepEqual(normalizeTradingSnapshot(expected, context), expected);
  assert.deepEqual(normalizeWorldComponents(saved).progression, saved.progression);
});

test("genuine HEAD farmer file and IndexedDB roundtrips preserve the entire progression ledger", async () => {
  const saved = archived();
  const file = parseWorldFile(exportWorldFile(saved));
  assert.deepEqual(normalizeWorldComponents(file).progression, saved.progression);
  const indexedDB = new IDBFactory();
  const first = new WorldStorage({ indexedDB });
  await first.save(file);
  await first.close();
  const second = new WorldStorage({ indexedDB });
  const loaded = await second.load();
  await second.close();
  assert.deepEqual(loaded.progression, saved.progression);
  assert.deepEqual(normalizeWorldComponents(loaded).progression, saved.progression);
});

test("legacy restock and same-profession jobsite reclaim keep the exact v1 roster and prices", (t) => {
  const saved = archived();
  const context = createWorldContext(saved.world);
  const trading = new Trading({ context });
  t.after(() => trading.dispose());
  const expected = saved.progression.trading;
  assert.equal(trading.load(expected), true);
  assert.deepEqual(trading.serialize(), expected);
  const npc = expected.npcs[0];
  const restock = trading.prepareRestock(npc.id, oldOptions(7000));
  assert.ok(restock);
  assert.deepEqual(trading.serialize(), expected, "preparation does not migrate or restock");
  assert.equal(trading.commit(restock).ok, true);
  const restocked = structuredClone(expected);
  Object.assign(restocked.npcs[0], {
    clock: { day: 3, time: 7000 }, restocks: 2, lastRestockTime: 7000,
    offers: npc.offers.map(offer => ({ ...offer, uses: 0 })),
  });
  assert.deepEqual(trading.serialize(), restocked);
  assert.equal(trading.commit(restock).ok, false);
  for (const jobsite of [null, npc.jobsite]) {
    const plan = trading.prepareAssign(npc.id, { profession: "farmer", jobsite }, oldOptions(7000));
    assert.ok(plan);
    assert.equal(trading.commit(plan).ok, true);
    assert.equal(trading.get(npc.id).offerVersion, 1);
    assert.deepEqual(trading.get(npc.id).offers, restocked.npcs[0].offers);
  }
  assert.deepEqual(trading.serialize(), restocked);
  saved.progression.trading = restocked;
  assert.deepEqual(normalizeWorldComponents(parseWorldFile(exportWorldFile(saved))).progression, saved.progression);
});

test("catalog v2 adds only the carrot offer without rerolling historical seeded prices or metadata", () => {
  const context = createWorldContext(archived().world);
  for (const profession of TRADING_PROFESSIONS) {
    for (const id of ["fixture:village/npc/old-farmer", "fixture:village/npc/other-seed-choice"]) {
      const legacy = generateTraderOffers(id, profession, context, 1);
      const current = generateTraderOffers(id, profession, context, 2);
      assert.deepEqual(current.filter(offer => offer.id !== "farmer/planting-carrots"), legacy);
    }
  }
  const npc = archived().progression.trading.npcs[0];
  assert.deepEqual(generateTraderOffers(npc.id, npc.profession, context, 1),
    npc.offers.map(offer => ({ ...offer, uses: 0 })));
});

test("saved catalog validation rejects subsets, wrong versions, repricing and cross-catalog additions", () => {
  const saved = archived().progression.trading;
  const context = createWorldContext(archived().world);
  for (const mutate of [
    npc => npc.offers.pop(),
    npc => npc.offers.splice(1, 1),
    npc => npc.offerVersion = 2,
    npc => npc.offerVersion = 999,
    npc => npc.offers[4].inputs[0].count++,
    npc => npc.offers[1].maxUses++,
    npc => npc.offers.push(generateTraderOffers(npc.id, "farmer", context, 2)
      .find(offer => offer.id === "farmer/planting-carrots")),
  ]) {
    const bad = structuredClone(saved);
    mutate(bad.npcs[0]);
    assert.equal(normalizeTradingSnapshot(bad, context), null);
  }
  const current = structuredClone(saved);
  current.npcs[0].offerVersion = 2;
  current.npcs[0].offers = generateTraderOffers(current.npcs[0].id, "farmer", context, 2);
  assert.ok(normalizeTradingSnapshot(current, context));
  for (const mutate of [
    npc => npc.offerVersion = 1,
    npc => npc.offers.splice(npc.offers.findIndex(o => o.id === "farmer/planting-carrots"), 1),
  ]) {
    const bad = structuredClone(current);
    mutate(bad.npcs[0]);
    assert.equal(normalizeTradingSnapshot(bad, context), null);
  }
});

test("new farmer carrot cost and exhausted finite stock survive full preflight and file/IDB reload", async () => {
  const f = traderFixture("farmer");
  const offer = f.trading.offers(f.id).find(o => o.id === "farmer/planting-carrots");
  assert.equal(f.trading.get(f.id).offerVersion, 2);
  assert.equal(f.trading.get(f.id).offers.length, 7);
  assert.deepEqual(offer.inputs, [{ id: ITEM.EMERALD, count: 1 }]);
  assert.deepEqual(offer.output, { id: ITEM.CARROT, count: 2 });
  assert.equal(offer.maxUses, 4);
  inventoryStacks(f, [{ id: ITEM.EMERALD, count: 5 }]);
  const plan = f.trading.prepareTrade(f.id, offer.id, tradeOptions(f, 2000, 0, { count: 4 }));
  assert.ok(plan);
  assert.equal(f.trading.commit(plan).ok, true);
  assert.equal(f.inventory.count(ITEM.EMERALD), 1);
  assert.equal(f.inventory.count(ITEM.CARROT), 8);
  const saved = {
    version: 3,
    world: { version: 3, seed: f.context.seed, generatorVersion: f.context.generatorVersion,
      dimension: "overworld", edits: [] },
    gameplay: f.inventory.serialize(),
  };
  saved.progression = normalizeWorldComponents(saved).progression;
  saved.progression.trading = f.trading.serialize();
  const file = parseWorldFile(exportWorldFile(saved));
  assert.deepEqual(normalizeWorldComponents(file).progression, saved.progression);
  const indexedDB = new IDBFactory();
  const storage = new WorldStorage({ indexedDB });
  await storage.save(file);
  await storage.close();
  const reopened = new WorldStorage({ indexedDB });
  const loaded = await reopened.load();
  await reopened.close();
  assert.deepEqual(normalizeWorldComponents(loaded).progression, saved.progression);
  assert.deepEqual(loaded.gameplay, saved.gameplay);
  assert.equal(f.trading.load(loaded.progression.trading), true);
  assert.equal(f.trading.prepareTrade(f.id, offer.id, tradeOptions(f)), null);
  assert.equal(f.trading.get(f.id).offers.find(o => o.id === offer.id).uses, 4);
});

test("an actual profession change adopts v2 while a legacy same-profession assignment does not", (t) => {
  const saved = archived();
  const trading = new Trading({ context: createWorldContext(saved.world) });
  t.after(() => trading.dispose());
  const legacy = saved.progression.trading;
  const npc = legacy.npcs[0];
  Object.assign(npc, {
    profession: "unemployed", locked: false, xp: 0, offers: [],
    jobsite: null, restocks: 0, lastRestockTime: null,
  });
  assert.equal(trading.load(legacy), true);
  const plan = trading.prepareAssign(npc.id, {
    profession: "farmer", jobsite: archived().progression.trading.npcs[0].jobsite,
  }, oldOptions(7000));
  assert.ok(plan);
  assert.equal(trading.commit(plan).ok, true);
  assert.equal(trading.get(npc.id).offerVersion, 2);
  assert.equal(trading.get(npc.id).offers.length, 7);
});
