import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { IDBFactory } from "fake-indexeddb";
import { ITEM, getItem } from "../src/items.js";
import { normalizeWorldComponents } from "../src/save-preflight.js";
import { exportWorldFile, parseWorldFile, WorldStorage } from "../src/storage.js";
import {
  generateTraderOffers, MAX_TRADE_OFFERS, TRADE_ACQUISITION,
  TRADE_OFFER_VERSION, TRADING_PROFESSIONS,
} from "../src/trading-offers.js";
import { normalizeTradingSnapshot } from "../src/trading-state.js";
import { Trading } from "../src/trading.js";
import { createWorldContext } from "../src/world-spec.js";
import { traderFixture, stockTradeInputs, tradeOptions } from "./progression-fixture.js";

const fixture = JSON.parse(readFileSync(
  new URL("./fixtures/trading-v2-armorer.json", import.meta.url), "utf8"
));
const chainmail = [
  ["CHAINMAIL_BOOTS", 2, 1], ["CHAINMAIL_LEGGINGS", 2, 3],
  ["CHAINMAIL_HELMET", 3, 1], ["CHAINMAIL_CHESTPLATE", 3, 4],
];

test("genuine pre-change v2 merchant keeps offers/stock byte-for-byte through normalization, file and IDB load", async (t) => {
  assert.equal(fixture.sourceCommit, "4f0f7d98322152ce8890b837be09e84b62e1c14a");
  const saved = structuredClone(fixture.archive), context = createWorldContext(saved.world);
  const expected = JSON.stringify(saved.progression.trading);
  const trading = new Trading({ context });
  t.after(() => trading.dispose());
  assert.equal(saved.progression.trading.npcs[0].offers.length, 7);
  assert.equal(saved.progression.trading.npcs[0].offers[1].uses, 3);
  assert.equal(saved.progression.trading.npcs[0].restocks, 1);
  assert.equal(JSON.stringify(normalizeTradingSnapshot(saved.progression.trading, context)), expected);
  assert.equal(trading.load(saved.progression.trading), true);
  assert.equal(JSON.stringify(trading.serialize()), expected);
  const file = parseWorldFile(exportWorldFile(saved));
  assert.equal(JSON.stringify(normalizeWorldComponents(file).progression.trading), expected);
  const indexedDB = new IDBFactory();
  const storage = new WorldStorage({ indexedDB });
  await storage.save(file);
  await storage.close();
  const reopened = new WorldStorage({ indexedDB });
  const loaded = await reopened.load();
  await reopened.close();
  assert.equal(JSON.stringify(loaded.progression.trading), expected);
  assert.deepEqual(loaded.gameplay, saved.gameplay);
  assert.equal(trading.load(loaded.progression.trading), true);
  assert.equal(JSON.stringify(trading.serialize()), expected);
});

test("catalog v3 adds only four chainmail offers per smith and never rerolls v1/v2 prices or metadata", () => {
  for (const seed of ["", "chainmail-catalog", "cedar-valley"]) {
    const context = createWorldContext({ seed, generatorVersion: 4, dimension: "overworld" });
    for (const profession of TRADING_PROFESSIONS) {
      const id = `fixture:${profession}/catalog`;
      const v1 = generateTraderOffers(id, profession, context, 1);
      const v2 = generateTraderOffers(id, profession, context, 2);
      const v3 = generateTraderOffers(id, profession, context);
      assert.equal(TRADE_OFFER_VERSION, 3);
      assert.deepEqual(v2.filter(o => o.id !== "farmer/planting-carrots"), v1);
      assert.deepEqual(v3.filter(o => !o.id.includes("/chainmail-")), v2);
      assert.ok(v3.length <= MAX_TRADE_OFFERS);
      if (!["armorer", "toolsmith"].includes(profession)) continue;
      assert.equal(v3.length, v2.length + 4);
      for (const [symbol, level, price] of chainmail) {
        const item = getItem(ITEM[symbol]);
        const offer = v3.find(o => o.output.id === item.id);
        assert.deepEqual(offer.inputs, [{ id: ITEM.EMERALD, count: price }]);
        assert.deepEqual(offer.output, { id: item.id, count: 1, durability: item.durability });
        assert.equal(offer.level, level);
        assert.equal(offer.maxUses, 12);
        assert.equal(offer.uses, 0);
        assert.deepEqual(TRADE_ACQUISITION[symbol].soldBy, ["armorer", "toolsmith"]);
      }
    }
  }
});

test("historical catalogs of every profession normalize without adding offers or changing used stock", () => {
  const context = createWorldContext(fixture.archive.world);
  for (const profession of TRADING_PROFESSIONS) for (const version of [1, 2]) {
    // Authored ledger exercises every catalog; the separate v2 archive above
    // was generated by executing the genuine pre-change production code.
    const saved = structuredClone(fixture.archive.progression.trading);
    const npc = saved.npcs[0];
    Object.assign(npc, {
      profession, offerVersion: version, xp: 250, jobsite: null,
      offers: generateTraderOffers(npc.id, profession, context, version)
        .map((offer, index) => ({ ...offer, uses: Math.min(index + 1, offer.maxUses) })),
    });
    assert.equal(JSON.stringify(normalizeTradingSnapshot(saved, context)), JSON.stringify(saved));
    const upgraded = structuredClone(saved);
    upgraded.npcs[0].offerVersion = 3;
    if (["armorer", "toolsmith"].includes(profession))
      assert.equal(normalizeTradingSnapshot(upgraded, context), null);
  }
});

test("both smith professions unlock every piece by paid level progression, never novice access", (t) => {
  for (const profession of ["armorer", "toolsmith"]) {
    const f = traderFixture(profession);
    t.after(() => { f.trading.dispose(); f.inventory.dispose(); });
    const pay = (suffix, count = 1) => {
      const offer = f.trading.offers(f.id).find(o => o.id === `${profession}/${suffix}`);
      assert.ok(offer);
      // Authored finite payment, not a mined-resource Survival journey.
      stockTradeInputs(f, offer, count);
      const plan = f.trading.prepareTrade(f.id, offer.id, tradeOptions(f, 2000, 0, { count }));
      assert.ok(plan);
      assert.equal(f.trading.commit(plan).ok, true);
      const paid = JSON.stringify([f.inventory.serialize(), f.trading.serialize()]);
      assert.equal(f.trading.commit(plan).ok, false);
      assert.equal(JSON.stringify([f.inventory.serialize(), f.trading.serialize()]), paid);
    };
    assert.equal(f.trading.prepareTrade(f.id, `${profession}/chainmail-boots`, tradeOptions(f)), null);
    pay("coal", 5);
    assert.equal(f.trading.get(f.id).xp, 10);
    assert.ok(f.trading.offers(f.id).some(o => o.output.id === ITEM.CHAINMAIL_BOOTS));
    assert.equal(f.trading.prepareTrade(f.id, `${profession}/chainmail-helmet`, tradeOptions(f)), null);
    pay("iron", 6);
    assert.equal(f.trading.get(f.id).xp, 70);
    for (const suffix of ["boots", "leggings", "helmet", "chestplate"]) {
      pay(`chainmail-${suffix}`);
      assert.equal(f.inventory.count(ITEM[`CHAINMAIL_${suffix.toUpperCase()}`]), 1);
      assert.equal(f.inventory.count(ITEM.EMERALD), 0);
      assert.equal(f.trading.get(f.id).offers.find(o => o.id === `${profession}/chainmail-${suffix}`).uses, 1);
    }
  }
});
